import Head from 'next/head'
import Navbar from '../comps/Navbar'
import Footer from '../comps/Footer'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Image from 'next/image'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MicheleMaretto</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h4 class="wordCarousel">
        <span>Michele Maretto </span>
        <div>
            <ul class="flip4">
                <li>Buildings</li>
                <li>Renovation</li>
                <li>Design</li>
                <li>Architecture</li>
            </ul>
        </div>
    </h4>
    </div>
  )
}
